### ISSUE TITLE
Add g3proxy

### ISSUE THREAD

**Issue by zh-jq-b** [awesome-selfhosted/awesome-selfhosted-data#1088]
```yaml
name: g3proxy
website_url: "https://github.com/bytedance/g3/g3proxy/"
source_code_url: "https://github.com/bytedance/g3"
description: "Forward proxy server, support Proxy Chaining, Protocol Inspection, MITM Interception, ICAP Adaptation, Transparent Proxy."
licenses:
  - Apache-2.0
platforms:
  - Rust
  - Deb
  - Docker
tags:
  - Proxy
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
