### ISSUE TITLE
Add go-proxy

### ISSUE THREAD

**Issue by D1noD3v** [awesome-selfhosted/awesome-selfhosted-data#1157]
```yaml
name: "go-proxy"
source_code_url: "https://github.com/yusing/go-proxy/tree/feat/godoxy-agent"
description: "A Easy to use reverse proxy with docker integration. Also features idlesleeper, shutting down idle containers and starting them when traffic arrives."
licenses:
  - MIT
platforms:
  - Go
tags:
  - Web Servers
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
