### ISSUE TITLE
Add Plant-it

### ISSUE THREAD

**Issue by Rabenherz112** [awesome-selfhosted/awesome-selfhosted-data#1189]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "Plant-it"
# URL of the software project's homepage
website_url: "https://plant-it.org/"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/MDeLuise/plant-it"
# description of what the software does, shorter than 250 characters, sentence case
description: "Gardening companion app that helps you take care of your plants."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - GPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Miscellaneous
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.

> [Project under "active" development, some features may be unstable or change in the future. A first release version is planned to be packed soon].
