### ISSUE TITLE
Add TrueConf Server

### ISSUE THREAD

**Issue by TrueConf** [awesome-selfhosted/awesome-selfhosted-data#1207]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
name: "TrueConf Server"
website_url: "https://trueconf.com/products/server/video-conferencing-server.html"
source_code_url: "proprietary"
description: "A self-hosted platform for your corporate communications, based on the advanced architecture, with support for UltraHD video conferencing, built-in messenger with personal and group chats, and a free version for up to 1,000 users."
licenses:
  - Proprietary
platforms:
  - Go
  - C++
tags:
  - Communication - Video Conferencing 
  - Communication - Custom Communication Systems
depends_3rdparty: false
related_software_url: "trueconf.com/download"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
