### ISSUE TITLE
Add Forward Email

### ISSUE THREAD

**Issue by titanism** [awesome-selfhosted/awesome-selfhosted-data#1259]
```yaml
name: "Forward Email"
website_url: "https://forwardemail.net"
source_code_url: "https://github.com/forwardemail/forwardemail.net"
description: "Privacy-focused encrypted email for everyone. All-in-one alternative to Gmail + Mailchimp + Sendgrid."
licenses:
  - BUSL-1.1
  - MPL-2.0
platforms:
  - JavaScript
  - Nodejs
  - Docker
tags:
  - Communication - Email - Complete Solutions
depends_3rdparty: false
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.

---

Founder of Forward Email here (@forwardemail).  Happy to answer any questions or submit a PR directly if that works best.

We also recently published an `awesome` list of our own at <https://github.com/forwardemail/awesome-mail-server-providers> and referenced this list too! 🙏
