### ISSUE TITLE
Add dedicated AI section

### ISSUE THREAD

**Issue by Sparkenstein** [awesome-selfhosted/awesome-selfhosted-data#1261]
Continuing from https://github.com/awesome-selfhosted/awesome-selfhosted/issues/4190

We need a dedicated "AI" section for awesome selfhosted AI apps. the list is quiet big and unfotunately existing repos that track it are mostly outdated

**Comment by nodiscc** [comment]
What would be the description for this category/tag and which items would you link it to?

**Comment by kokomo123** [comment]
Per the thread, I guess something like this?  

<img width="850" alt="Image" src="https://github.com/user-attachments/assets/d9f71c17-6313-45f7-921a-d5501673672f" />

**Comment by guest20** [comment]
"AI" seems like a pretty wide category - maybe it's worth focusing on what the AI does (text generator, image generator, chat bot), instead of just being "an AI thingy"?

**Comment by Ki-er** [comment]
We could do the same as software development and have:

artificial-intelligence.yml
```yml 
name: Artificial Intelligence (AI)
description: '[Artificial Intelligence (AI)](https://en.wikipedia.org/wiki/Software_development) refers to the capability of [computational systems](https://en.wikipedia.org/wiki/Computer) to perform tasks typically associated with [human intelligence](https://en.wikipedia.org/wiki/Human_intelligence), such as learning, reasoning, problem-solving, perception, and decision-making.
redirect:
  - title: Artificial Intelligence - Image Generations
    url: '#software-development---image-generators'
cont...
```
artificial-intelligence---image generators.yml
```yml
Include yml for image generators tag
```
and so on and so on

Some tags such as the above (text generator, image generator, chat bot) but also `accompanying projects` could be added such as [Actual-ai](https://github.com/sakowicz/actual-ai) and [paperless-ai](https://github.com/clusterzx/paperless-ai). 

Obviously there should be 3 or more per category but those are just suggestions.
