### ISSUE TITLE
Add Statistics for Strava

### ISSUE THREAD

**Issue by robiningelbrecht** [awesome-selfhosted/awesome-selfhosted-data#1340]
```yaml
# software name
name: "Statistics for Strava"
# URL of the software project's homepage
website_url: "https://github.com/robiningelbrecht/statistics-for-strava"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/robiningelbrecht/statistics-for-strava"
# description of what the software does, shorter than 250 characters, sentence case
description: "Self-hosted statistics generated using Strava data."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - AGPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - PHP
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Miscellaneous
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: true
# (optional) link to an interactive demo of the software
demo_url: "https://statistics-for-strava.robiningelbrecht.be/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
