### ISSUE TITLE
Add Garmin Grafana

### ISSUE THREAD

**Issue by arpanghosh8453** [awesome-selfhosted/awesome-selfhosted-data#1370]
```yaml
name: "Garmin-Grafana"
website_url: "https://github.com/arpanghosh8453/garmin-grafana"
source_code_url: "https://github.com/arpanghosh8453/garmin-grafana"
description: "A Dockerized python Script to fetch Garmin health data and populate in an InfluxDB Database, for visualization of long term health trends with Grafana"
licenses:
  - BSD-3-Clause
platforms:
  - Python
  - Docker
  - Nix
tags:
  - Personal Dashboards
  - Analytics
  - Monitoring
  - Software Development
depends_3rdparty: true
demo_url: "https://github.com/arpanghosh8453/garmin-grafana/raw/main/Grafana_Dashboard/Garmin-Grafana-Dashboard-Preview.png"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
