### ISSUE TITLE
Add Quay

### ISSUE THREAD

**Issue by JustGitting** [awesome-selfhosted/awesome-selfhosted-data#1371]
```yaml
# software name
name: "Quay"
# URL of the software project's homepage
website_url: "https://www.projectquay.io/"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/quay/quay"
# description of what the software does, shorter than 250 characters, sentence case
description: "Build, Store, and Distribute your Applications and Containers "
# list of license identifiers
licenses:
  - Apache-2.0
# list of languages/platforms
platforms:
  - Podman
  - Kubernetes
  - OpenShift
  - Docker
# list of tags (categories)
tags:
  - NA
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: false
# (optional) link to an interactive demo of the software
demo_url: "https://quay.io/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
