### ISSUE TITLE
Add Cicada

### ISSUE THREAD

**Issue by JustGitting** [awesome-selfhosted/awesome-selfhosted-data#1372]
```yaml
# software name
name: "Cicada"
# URL of the software project's homepage
website_url: "https://github.com/mebtte/cicada"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/mebtte/cicada"
# description of what the software does, shorter than 250 characters, sentence case
description: "A multi-user music service for self-hosting."
# list of license identifiers, see https://github.com/mebtte/cicada/blob/v2/license for the full list of licenses
licenses:
  - GPL-3.0
# list of languages/platforms
platforms:
  - Binary
  - Docker
  - Docker Compose
# list of tags (categories)
tags:
  - N/A
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: false
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.

Reference:
Add [Cicada] to [Media Streaming - Audio Streaming] #4084
https://github.com/awesome-selfhosted/awesome-selfhosted/issues/4084
