### ISSUE TITLE
Add SNIP

### ISSUE THREAD

**Issue by lookshe** [awesome-selfhosted/awesome-selfhosted-data#1408]
```yaml
# software name
name: "SNIP"
# URL of the software project's homepage
website_url: "https://github.com/MercanoGlobal/SNIP"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/MercanoGlobal/SNIP"
# description of what the software does, shorter than 250 characters, sentence case
description: "SNIP is a powerful Open-Source PHP Pastebin, with the aim of keeping a simple and easy to use user interface."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - GPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - PHP
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Pastebins
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/awesome-foss/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
