### ISSUE TITLE
Github actions: workflow `ci` does not run automatically after commits from the `update-metadata` workflow

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted-data#15]
https://github.com/orgs/community/discussions/25702

 > If an action pushes code using the repository’s GITHUB_TOKEN, a new workflow will not run even when the repository contains a workflow configured to run when push events occur. Please create a personal access token in repo setting (write permission accordingly), replace GITHUB_TOKEN in your ‘inc-counter.yml’, code as below, thanks.

```yaml
- name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT}}
```
