### ISSUE TITLE
Add Logseq

### ISSUE THREAD

**Issue by UserCr4ig** [awesome-selfhosted/awesome-selfhosted-data#224]
```yaml
# software name
name: Logseq
# URL of the software project's homepage
website_url: https://logseq.com
# URL where the full source code of the program can be downloaded
source_code_url: https://github.com/logseq/logseq
# description of what the software does, shorter than 250 characters, sentence case
description: A very good alternative to obsidianMD (Knowledge-base CMS)
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - AGPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - content-management-systems-cms
  - knowledge-management-tools
# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: yes
# (optional) link to an interactive demo of the software
demo_url: https://logseq-demo.devops.bike
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
related_software_url: https://hub.logseq.com/use-cases/1Sr4awszMQzD4GM5KvWim7/10-must-have-plugins-for-logseq/jgDG2ZVkeZGSQHXUNkWroo

```
NOTE : Consider adding this instruction to host it because official documentation is not very handy : https://devops.bike/publish-your-notes-as-site

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x ] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x ] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ x] Any software project you are adding to the list is actively maintained.
- [ x] Any software project you are adding was first released more than 4 months ago.
- [ x] Any software project you are adding has working installation instructions.
- [ x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
