### ISSUE TITLE
Add guix-forge

### ISSUE THREAD

**Issue by jgarte** [awesome-selfhosted/awesome-selfhosted-data#226]
```yaml
# guix-forge
name: "guix-forge"
# URL of the software project's homepage
website_url: "https://guix-forge.systemreboot.net/manual/dev/en/"
# URL where the full source code of the program can be downloaded
source_code_url: "https://git.systemreboot.net/guix-forge/"
# description of what the software does, shorter than 250 characters, sentence case
description: "guix-forge is a Guix service that lets you run a complete software forge in the manner of GitHub"
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - GPLv3+
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Scheme
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Automation
# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: no
# (optional) link to an interactive demo of the software
demo_url: https://archive.org/details/arun-isaac-on-guix-forge
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ ] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ ] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [ ] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
