### ISSUE TITLE
Add Review Board

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted-data#26]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below:

```yaml
name: "Review Board"
website_url: "https://www.reviewboard.org/"
source_code_url: "https://github.com/reviewboard/reviewboard"
description: "Extensible and friendly code review tool for projects and companies of all sizes."
licenses:
  - MIT
platforms:
  - Python
  - Deb
  - Docker
tags:
  - Software Development - Project Management
vei
demo_url: "https://demo.reviewboard.org/"
```

To ensure your issue is dealt with swiftly please check the following (check the boxes `[x]`):
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] If creating new `tags`, any tag has the minimum requirement of 3 items. If not, your addition may be inserted into `Miscellaneous`.
