### ISSUE TITLE
Add Janus WebRTC Server

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted-data#28]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below:

```yaml
# software/janus.yml
name: "Janus"
website_url: "https://janus.conf.meetecho.com/"
source_code_url: "https://github.com/meetecho/janus-gateway"
description: "General-purpose, lightweight, minimalist WebRTC Server."
licenses:
  - GPL-3.0
platforms:
  - C
tags:
  - Communication - Video Conferencing
demo_url: "https://janus.conf.meetecho.com/demos.html"
```

To ensure your issue is dealt with swiftly please check the following (check the boxes `[x]`):
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Submit one item per pull request. This eases reviewing and speeds up inclusion.
- [x] Values for `platform` are the main **server-side** requirements for the software. Don't include frameworks or specific dialects.
- [x] Any software project you are adding to the list is actively maintained.
- [x] If creating new `tags`, any tag has the minimum requirement of 3 items. If not, your addition may be inserted into `Miscellaneous`.
