### ISSUE TITLE
Add La Digitale

### ISSUE THREAD

**Issue by stefanauss** [awesome-selfhosted/awesome-selfhosted-data#295]
```yaml
# software name
name: "La Digitale"
# URL of the software project's homepage
website_url: "https://ladigitale.dev/"
# URL where the full source code of the program can be downloaded
source_code_url: "https://codeberg.org/ladigitale"
# description of what the software does, shorter than 250 characters, sentence case
description: "Suite of 30+ single-task web applications to aid in learning and teaching processes, both in class and remotely (documentation in French)."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - AGPL-3.0
  - GPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Javascript
  - PHP
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Learning and Courses
# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: no
# (optional) link to an interactive demo of the software
demo_url: "https://ladigitale.dev/#outils"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ ] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
