### ISSUE TITLE
Add Exatorrent project is still alive and development is slow but satble

### ISSUE THREAD

**Issue by mckaygerhard** [awesome-selfhosted/awesome-selfhosted-data#348]
```yaml
# software name
name: exatorrent
# URL of the software project's homepage
website_url: https://github.com/varbhat/exatorrent
# URL where the full source code of the program can be downloaded
source_code_url: https://github.com/varbhat/exatorrent
# description of what the software does, shorter than 250 characters, sentence case
description: Easy to Use Torrent Client. Can be hosted in Cloud. Files can be streamed in Browser/Media Player. Files also are preview inside!
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - [GPL-v3](https://github.com/varbhat/exatorrent/blob/main/LICENSE)
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Go
  - Svelte
  - TypeScript
  - JavaScript
  - Nodejs
  - Unix (for development is exclusive)
  - Cross platform
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - [go](https://github.com/topics/go)
  - [golang](https://github.com/topics/golang) 
  - [torrent](https://github.com/topics/torrent)
  - [cloud](https://github.com/topics/cloud)
  - [bittorrent](https://github.com/topics/bittorrent) 
  - [bittorrent-client](https://github.com/topics/bittorrent-client)
  - [bittorrent-client-gui](https://github.com/topics/qbittorrent)
  - [self-hosted](https://github.com/topics/self-hosted)
  - [gui](https://github.com/topics/gui)
  - [web](https://github.com/topics/web)
# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: no
# (optional) link to an interactive demo of the software
# demo_url: "https://my.awesome.softwar.e/demo"
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
# related_software_url: "https://my.awesome.softwar.e/apps"
```

- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

### notes

Exatorrent was archived due mistakes and plans that now were stabilized, its under development but not so active, is focused on stability
