### ISSUE TITLE
Add Crypta

### ISSUE THREAD

**Issue by thanhnguyen2187** [awesome-selfhosted/awesome-selfhosted-data#431]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
name: "Crypta"
website_url: "https://github.com/thanhnguyen2187/crypta"
source_code_url: "https://github.com/thanhnguyen2187/crypta"
description: "Offline-first code snippet manager."
licenses:
  - MIT
platforms:
  - Javascript
tags:
  - Pastebins
depends_3rdparty: false
demo_url: "https://thanhnguyen2187.github.io/crypta"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
