### ISSUE TITLE
Add Keploy

### ISSUE THREAD

**Issue by Arindam200** [awesome-selfhosted/awesome-selfhosted-data#475]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "Keploy"
# URL of the software project's homepage
website_url: "https://keploy.io"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/keploy/keploy"
# description of what the software does, shorter than 250 characters, sentence case
description: "Keploy is a developer-centric backend testing tool. It makes backend tests with built-in-mocks, faster than unit tests, from user traffic, making it easy to use, powerful, and extensible.."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - Apache-2.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Java
  - Python
  - Nodejs
  - Go
  - JavaScript
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Automation
  - Testing  
  - API Management
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: false
# (optional) link to an interactive demo of the software
demo_url: "https://www.youtube.com/watch?v=23yQaY81Zho"
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
related_software_url: "https://my.awesome.softwar.e/apps"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
