### ISSUE TITLE
Add Jauth

### ISSUE THREAD

**Issue by Jipok** [awesome-selfhosted/awesome-selfhosted-data#568]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
name: "Jauth"
website_url: "https://github.com/Jipok/Jauth"
source_code_url: "[https://gitlab.com/awesome/software"](https://github.com/Jipok/Jauth)
description: "Lightweight SSL/TLS reverse proxy with authorization(via Telegram and SSH) for self-hosted apps."
licenses:
  - GPL-3.0
platforms:
  - Go
tags:
  - Proxy
demo_url: "https://j.ateam.undo.it/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
