### ISSUE TITLE
Add Moonlight Panel

### ISSUE THREAD

**Issue by gOOvER** [awesome-selfhosted/awesome-selfhosted-data#600]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "Moonlight Panel"
# URL of the software project's homepage
website_url: "https://moonlightpanel.xyz"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/Moonlight-Panel/Moonlight"
# description of what the software does, shorter than 250 characters, sentence case
description: "Moonlight is a new free and open-source alternative to Pterodactyl, allowing users to create their own hosting platform and host all sorts of game servers in Docker containers."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - CC0 1.0 Universal
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - C#
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Games
  - administrative-utilities--control-panels
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: false
# (optional) link to an interactive demo of the software
demo_url: "https://my.awesome.softwar.e/demo"
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
related_software_url: "https://my.awesome.softwar.e/apps"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
