### ISSUE TITLE
Add NUTCase

### ISSUE THREAD

**Issue by ArthurMitchell42** [awesome-selfhosted/awesome-selfhosted-data#614]
Can I propose the following tool for interfacing NUT UPS devices to metric scrapers such as Prometheus, JSON consumers such as Uptime Kuma and HomePage.
It also provides a GUI to visualise the current status of devices.

```yaml
name: "NUTCase - NUT and APC GUI, metrics and JSON tool for UPS's"
website_url: "https://github.com/ArthurMitchell42/nutcase/wiki"
source_code_url: "https://github.com/ArthurMitchell42/nutcase"
description: "Links network-ups-tools (NUT) and APC daemon UPS devices to metric scrapers such as Prometheus, JSON consumers such as HomePage and supports a GUI to visualise current UPS status."
licenses:
  - AGPL-3.0
platforms:
  - Python
  - Docker
tags:
  - Status / Uptime pages
  - Monitoring
  - Metrics & Metric Collection
depends_3rdparty: false
demo_url: ""
related_software_url: ""
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [ x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ x] Any software project you are adding to the list is actively maintained.
- [ x] Any software project you are adding was first released more than 4 months ago.
- [ x] Any software project you are adding has working installation instructions.
- [ x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
