### ISSUE TITLE
Add Readeck

### ISSUE THREAD

**Issue by tanrak** [awesome-selfhosted/awesome-selfhosted-data#644]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
name: "Readeck"
website_url: "https://readeck.org/en/"
source_code_url: "https://codeberg.org/readeck/readeck"
description: "Readeck is a simple web application that lets you save the precious readable content of web pages you like and want to keep forever. See it as a bookmark manager and a read later tool."
licenses:
  - GNU Affero General Public License v3.0
platforms:
  - Go
  - Docker
tags:
  - Bookmarks and Link Sharing
  - Archiving and Digital Preservation (DP)
related_software_url: "https://codeberg.org/readeck/browser-extension"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [ ] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.
