### ISSUE TITLE
Add Wavelog

### ISSUE THREAD

**Issue by HB9HIL** [awesome-selfhosted/awesome-selfhosted-data#690]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
name: "Wavelog"
website_url: "https://www.wavelog.org"
source_code_url: "https://github.com/wavelog/wavelog"
description: "Webbased Logging Software for Radio Amateurs. Enhanced logging in your browser."
licenses:
  - MIT
platforms:
  - PHP
  - Docker
tags:
  - Miscellaneous
  - Amateur Radio
demo_url: "https://demo.wavelog.org"

```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
- [x] If you are adding software forked from another active project, please provide/link to a clear list of differences between both.

Wavelog is a Fork of [Cloudlog](https://github.com/magicbug/cloudlog). The clear difference is much better stability, less bugs, more features and a huge performance improvement. There is no list existing which compares Wavelog with Cloudlog ([just this discussion](https://github.com/wavelog/wavelog/discussions/162)). Cloudlog is already listed, but Wavelog is not. 

The tag "Amateur Radio" is not existing (yet).
