### ISSUE TITLE
Add Diffuse.sh

### ISSUE THREAD

**Issue by Netherquark** [awesome-selfhosted/awesome-selfhosted-data#75]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "Diffuse.sh"
# URL of the software project's homepage
website_url: "https://diffuse.sh/about/"
# URL where the full source code of the program can be downloaded
source_code_url: "github.com/icidasset/diffuse/"
# description of what the software does, shorter than 250 characters, sentence case
description: "Diffuse is a decentralized music player consisting out of two main parts. One part is the music and the other is your data (eg. playlists), both of which are in locations of your choice. Meaning that there’s no central server for Diffuse, all of the processing happens on your device and all the data is in your control."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
 - https://github.com/icidasset/diffuse/blob/main/LICENSE
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Elm
  - Haskell
  - JavaScript
  - TypeScript

# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - media-streaming---audio-streaming.yml
# (optional, yes/no, default no) whether the software depends on a third-party service outside the user's control
depends_3rdparty: no
# (optional) link to an interactive demo of the software
demo_url: "https://diffuse.sh/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [ ] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [ ] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [ ] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [ ] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [ ] Any software project you are adding has working installation instructions.
