### ISSUE TITLE
Add OpenTTD

### ISSUE THREAD

**Issue by Fabizocker456** [awesome-selfhosted/awesome-selfhosted-data#756]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "OpenTTD"
# URL of the software project's homepage
website_url: "https://www.openttd.org/"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/OpenTTD/OpenTTD"
# description of what the software does, shorter than 250 characters, sentence case
description: "Open source transport tycoon simulation game"
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - GPL-2.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - C++
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Games
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: true
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
related_software_url: "https://bananas.openttd.org/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained. (most recent release: 3rd of May, 2024)
- [x] Any software project you are adding was first released more than 4 months ago. (2004)
- [x] Any software project you are adding has working installation instructions. ("download, unpack", and for a dedicated server https://wiki.openttd.org/en/Manual/Dedicated%20server)
