### ISSUE TITLE
Add CxReports

### ISSUE THREAD

**Issue by mstijak** [awesome-selfhosted/awesome-selfhosted-data#772]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
name: "CxReports"
website_url: "https://www.cx-reports.com/"
description: "Self-hosted reporting and PDF document generation with a user-friendly WYSIWYG template editor, API, automated email delivery, and robust security features. Free licenses available to registered users for low-volume reporting."
platforms:
  - Docker
tags:
  - Automation
  - Reporting
  - PDF
depends_3rdparty: true
demo_url: "https://demo.cx-reports.com"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.

CxReports is not free, but I cannot find instructions how to add it to the Non-Free section.
