### ISSUE TITLE
Add BookLogr

### ISSUE THREAD

**Issue by nodiscc** [awesome-selfhosted/awesome-selfhosted-data#791]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "BookLogr"
# URL of the software project's homepage
website_url: "https://github.com/Mozzo1000/booklogr"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/Mozzo1000/booklogr"
# description of what the software does, shorter than 250 characters, sentence case
description: "Web app designed to help you manage your personal book library with ease."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - Apache-2.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Python
  - Docker
  - Nodejs
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Automation
  - Calendar & Contacts
  - Bookmarks and Link Sharing
  - Pastebins
# (optional) link to an interactive demo of the software
demo_url: "https://demo.booklogr.app/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [ ] Any software project you are adding has working installation instructions.

To be revisited on 21 November 2024
