### ISSUE TITLE
Add HomeBox

### ISSUE THREAD

**Issue by Rabenherz112** [awesome-selfhosted/awesome-selfhosted-data#804]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "HomeBox"
# URL of the software project's homepage
website_url: "https://homebox.sysadminsmedia.com/en/"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/sysadminsmedia/homebox"
# description of what the software does, shorter than 250 characters, sentence case
description: "Inventory and organization system built for the Home User."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - AGPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Docker
  - Go
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Inventory Management
# (optional) link to an interactive demo of the software
demo_url: "https://homebox.fly.dev/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [ ] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.

First release Jun 19, wait until `2024-10-19`
