### ISSUE TITLE
Add Personal Management System

### ISSUE THREAD

**Issue by Volmarg** [awesome-selfhosted/awesome-selfhosted-data#822]
```yaml
# software name
name: "Personal Management System"
# URL of the software project's homepage
website_url: "https://volmarg.github.io/"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/Volmarg/personal-management-system"
# description of what the software does, shorter than 250 characters, sentence case
description: "Tool for managing all Your data in one place, passwords, contacts, costs, job days off etc."
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - MIT
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - PHP
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Personal Dashboards
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: false
# (optional) link to an interactive demo of the software
demo_url: "http://personal-management-system.pl/"
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.

---

My self note:
- project was already listed once, but was taken out because I've not maintained it for long time, I'm reviving it
