### ISSUE TITLE
Add Cup

### ISSUE THREAD

**Issue by sergi0g** [awesome-selfhosted/awesome-selfhosted-data#891]
Thanks for taking the time to suggest an addition to awesome-selfhosted! 

Please fill out information below (all fields are mandatory unless noted otherwise):

```yaml
# software name
name: "Cup"
# URL of the software project's homepage
website_url: "https://github.com/sergi0g/cup"
# URL where the full source code of the program can be downloaded
source_code_url: "https://github.com/sergi0g/cup"
# description of what the software does, shorter than 250 characters, sentence case
description: "🥤Docker container updates made easy"
# list of license identifiers, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/blob/master/licenses.yml for the full list of licenses
licenses:
  - AGPL-3.0
# list of languages/platforms, see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/platforms for the full list of platforms
platforms:
  - Rust
  - Docker
# list of tags (categories), see https://github.com/awesome-selfhosted/awesome-selfhosted-data/tree/master/tags for the full list of tags
tags:
  - Monitoring
# (optional, true/false, default false) whether the software depends on a third-party service outside the user's control
depends_3rdparty: false
# (optional) link to an interactive demo of the software
demo_url: 
# (optional) link to a list of clients/addons/plugins/apps/bots... for the software
related_software_url: 
```

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [X] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [X] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [X] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [X] Any software project you are adding to the list is actively maintained.
- [X] Any software project you are adding was first released more than 4 months ago.
- [X] Any software project you are adding has working installation instructions.
