### ISSUE TITLE
Add BZFlag

### ISSUE THREAD

**Issue by TheGiraffe3** [awesome-selfhosted/awesome-selfhosted-data#986]
```yaml
name: "BZFlag"
website_url: "https://bzflag.org"
source_code_url: "https://bzflag.org"
# Also the GitHub repository: https://github.com/BZFlag-Dev/bzflag
description: "Open-source multiplayer tank game around since the 1990s."
licenses:
  - LGPL
  - Mozilla 2.0
platforms:
  - C
  - C++
  - Perl
tags:
  - Games
depends_3rdparty: false?
# I think false; do dependencies like SDL2 count?
related_software_url: "https://forums.bzflag.org"
```

I am happy to make a pull request for this, but I'd like feedback on whether that would be acceptable first.

To ensure your issue is dealt with swiftly, please check the following (check the boxes `[x]`):
- [x] Submit one item per pull issue. This eases reviewing and speeds up inclusion.
- [x] You have searched the repository for any relevant [issues](https://github.com/awesome-selfhosted/awesome-selfhosted-data/issues) or [PRs](https://github.com/awesome-selfhosted/awesome-selfhosted-data/pulls), including closed ones.
- [x] Any software you are adding is not already listed at any of [awesome-sysadmin](https://github.com/n1trux/awesome-sysadmin), [staticgen.com](https://www.staticgen.com/), [staticsitegenerators.net](https://staticsitegenerators.net/), [dbdb.io](https://dbdb.io/browse).
- [x] Any software project you are adding to the list is actively maintained.
- [x] Any software project you are adding was first released more than 4 months ago.
- [x] Any software project you are adding has working installation instructions.
